# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predictor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpredictor.proto\x12\x13\x63om.asyncio_batcher\"\x16\n\x06Vector\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"\"\n\x10PredictionResult\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\x61\n\x0eKerasPredictor\x12O\n\x07Predict\x12\x1b.com.asyncio_batcher.Vector\x1a%.com.asyncio_batcher.PredictionResult\"\x00\x42-\n\x13\x63om.asyncio_batcherB\x0eKerasPredictorP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.asyncio_batcherB\016KerasPredictorP\001\242\002\003RTG'
  _globals['_VECTOR']._serialized_start=40
  _globals['_VECTOR']._serialized_end=62
  _globals['_PREDICTIONRESULT']._serialized_start=64
  _globals['_PREDICTIONRESULT']._serialized_end=98
  _globals['_KERASPREDICTOR']._serialized_start=100
  _globals['_KERASPREDICTOR']._serialized_end=197
# @@protoc_insertion_point(module_scope)
