version: "3.8"

services:
  scylla-node1:
    image: scylladb/scylla
    container_name: scylla-node1
    ports:
      - "9042:9042"
    environment:
      - CLUSTER_NAME=scylla-cluster
    command:
      - --alternator-port 8000
      - --alternator-write-isolation unsafe
      - --smp 2

  scylla-node2:
    image: scylladb/scylla
    container_name: scylla-node2
    ports:
      - "9043:9042"
    environment:
      - CLUSTER_NAME=scylla-cluster
    command:
      - --seeds="scylla-node1"
      - --alternator-port 8000
      - --alternator-write-isolation unsafe
      - --smp 2

  scylla-node3:
    image: scylladb/scylla
    container_name: scylla-node3
    ports:
      - "9044:9042"
    environment:
      - CLUSTER_NAME=scylla-cluster
    command:
      - --seeds="scylla-node1"
      - --alternator-port 8000
      - --alternator-write-isolation unsafe
      - --smp 2
